usephp: false
news: false
ssl: false
sitemap: false
sitemap_xml: false
rss: false
ogp: false
analytics: false
searchconsole: false
pagetop: true
articlesns: false
themecolor: false
safari: false
ie: false
chrome: false
fixedanchor_scss: false
fixedanchor_js: false
lightbox: true
svghexagon: false