<?php
$rootDir = '';
if($pageID === 'index') {
    $rootDir = './';
} else if($pageID === 'archive') {
    $rootDir = '../';
} ?>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="format-detection" content="telephone=no,address=no,email=no">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><?= $settings['appInfo']['name']; ?></title>

    <meta name="theme-color" content="#F24A00">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $rootDir ?>css/index.css">
</head>
<body data-spy="scroll" data-offset="80" class="<?= $pageID; ?>" id="<?= $pageID; ?>">
<div id="wrapper">
<div class="upper">

<header class="header" id="navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container">
            <a class="navbar-brand my-0 ml-auto mr-auto navbar_head" href="<?= $rootDir ?>"><h1><?= $settings['appInfo']['name']; ?></h1></a>
        </div>
    </nav>
</header>

<main class="main <?= $pageID; ?>main <?= $pageID; ?>Grid">
    <section class="container">
<?php if($pageID === 'index') {
    require_once(__DIR__ . '/_dirList.phtml');
} else if($pageID === 'archive') {
    require_once(__DIR__ . '/_imgList.phtml');
} ?>
    </section>
</main>

</div>

<footer class="footer mt-5 text-center">
    <small class="pt-1 pb-2 copyRight">Copyright <?= $settings['appInfo']['cpYear']; ?> <?= $settings['appInfo']['author']; ?></small>
</footer>

</div>
<script src="<?= $rootDir ?>js/lib.min.js" defer></script>
<script src="<?= $rootDir ?>js/app.min.js" defer></script>
</body>
</html>